
#
# Anyuid scc + Capabilities: IPC_LOCK and SYS_RESOURCE
#
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: kubedb-postgresql
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
  - IPC_LOCK
  - SYS_RESOURCE
defaultAddCapabilities: null
fsGroup:
  #type: MustRunAs
  # allow anyuid
  type: RunAsAny
groups: []
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  #type: MustRunAsRange
  # allow anyuid
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret