---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-bash-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-bash-test
  labels:
    app: pod-bash-test
spec:
  terminationGracePeriodSeconds: 0
  nodeSelector:
    role: storage-node
  containers:
    - name: pod-bash-test
      image: "centos:7" # Run as root
      args: ["/bin/sh", "-c", "whoami; while true; do MSG=\"$(date) - $HOSTNAME - hello world\"; echo \"$MSG\"; echo \"$MSG\" >> /mnt/ceph-pod-bash-test/log.txt;  sleep 10; done"]
      volumeMounts:
      - name: cephvol
        mountPath: "/mnt/ceph-pod-bash-test"
  volumes:
    - name: cephvol
      persistentVolumeClaim:
        claimName: pod-bash-test

# 