# Example from an Ansible Playbook
---
- hosts:
  - all
  #gather_facts: False # Faster

  tasks:
  #- ping:
  - shell: whoami
    register: out
  - debug: msg="{{ out }}"
  - debug:
      msg: "inventory_hostname {{ inventory_hostname }}"
  - name: Get disk info
    shell: lsblk
    register: out
  - debug: msg="{{ out }}"
# Induce an exception to see what happens
# - ping:
#     data: crash